// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PCDestino.Infrastructure.Persistence;

#nullable disable

namespace PCDestino.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819220718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PCDestino.Domain.Catalog.AccessibilityFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_accessibility_features");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accessibility_features_code");

                    b.ToTable("accessibility_features", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Catalog.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_slug");

                    b.HasIndex("StateCode", "Name")
                        .HasDatabaseName("ix_cities_state_code_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessibilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("accessibility_score");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("address_line");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("postal_code");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_places_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("CityId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_places_city_id_slug");

                    b.HasIndex("CityId", "Status", "Kind")
                        .HasDatabaseName("ix_places_city_id_status_kind");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Places.PlaceAccessibilityFeature", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("AccessibilityFeatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessibility_feature_id");

                    b.Property<string>("Evidence")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evidence");

                    b.HasKey("PlaceId", "AccessibilityFeatureId")
                        .HasName("pk_place_accessibility_features");

                    b.HasIndex("AccessibilityFeatureId")
                        .HasDatabaseName("ix_place_accessibility_features_accessibility_feature_id");

                    b.ToTable("place_accessibility_features", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Places.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessibilityRating")
                        .HasColumnType("integer")
                        .HasColumnName("accessibility_rating");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moderated_at");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("PlaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_place_id_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reviews_status_created_at");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Users.Favorite", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "PlaceId")
                        .HasName("pk_favorites");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_favorites_place_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_favorites_user_id_created_at");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Users.PointEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_point_events");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_point_events_city_id");

                    b.HasIndex("Type", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_point_events_type_reference_id");

                    b.HasIndex("UserId", "CityId", "CreatedAt")
                        .HasDatabaseName("ix_point_events_user_id_city_id_created_at");

                    b.ToTable("point_events", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<bool>("ParticipateInRanking")
                        .HasColumnType("boolean")
                        .HasColumnName("participate_in_ranking");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_external_id");

                    b.HasIndex("CityId", "ParticipateInRanking")
                        .HasDatabaseName("ix_user_profiles_city_id_participate_in_ranking");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("PCDestino.Domain.Places.Place", b =>
                {
                    b.HasOne("PCDestino.Domain.Catalog.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("PCDestino.Domain.Places.PlaceAccessibilityFeature", b =>
                {
                    b.HasOne("PCDestino.Domain.Catalog.AccessibilityFeature", "AccessibilityFeature")
                        .WithMany()
                        .HasForeignKey("AccessibilityFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_place_accessibility_features_accessibility_features_accessi");

                    b.HasOne("PCDestino.Domain.Places.Place", "Place")
                        .WithMany("AccessibilityFeatures")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_accessibility_features_places_place_id");

                    b.Navigation("AccessibilityFeature");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PCDestino.Domain.Places.Review", b =>
                {
                    b.HasOne("PCDestino.Domain.Places.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_places_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PCDestino.Domain.Users.Favorite", b =>
                {
                    b.HasOne("PCDestino.Domain.Places.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_places_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PCDestino.Domain.Users.PointEvent", b =>
                {
                    b.HasOne("PCDestino.Domain.Catalog.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_point_events_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("PCDestino.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("PCDestino.Domain.Catalog.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_profiles_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("PCDestino.Domain.Places.Place", b =>
                {
                    b.Navigation("AccessibilityFeatures");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
